server:
  port: 8084
spring:
  application:
    name: searchservice
  cloud:
    nacos:
      server-addr: localhost:8848
  rabbitmq:
    # 192.168.136.132
    host: 192.168.200.130
    port: 5672
    virtual-host: /
    username: itcast
    password: 123321
logging:
  level:
    cn.itcast: debug
  pattern:
    dateformat: MM-dd HH:mm:ss:SSS